#!/usr/bin/env Rscript

Sys.setenv(VAULT_ADDR = "https://vault.dide.ic.ac.uk:8200",
           VAULTR_AUTH_METHOD = "github")


add_deploy_key <- function(overwrite = FALSE) {
  user <- "mrc-ide"
  repo <- "naomi-orderly"
  user_repo <- paste(user, repo, sep = "/")

  url_key <- sprintf("https://github.com/%s/settings/keys/new", user_repo)
  vault_path <- sprintf("secret/hiv-orderly/deploy-keys/%s", user_repo)

  vault <- vaultr::vault_client(login = TRUE)

  if (!is.null(vault$read(vault_path)) && !overwrite) {
    message(sprintf("Deploy key already exists for '%s'", user_repo))
    message(sprintf("Public key is:\n\n%s", vault$read(vault_path, "pub")))
    return()
  }

  key <- openssl::rsa_keygen()
  str_key <- openssl::write_pem(key, NULL)
  str_pub <- openssl::write_ssh(key, NULL)
  data <- list(key = str_key, pub = str_pub)

  message(sprintf("Writing keys to vault at '%s'", vault_path))
  vault$write(vault_path, data)
  message(sprintf("Add the public key to github at\n  %s\n", url_key))
  message(sprintf("with content:\n\n%s\n", data$pub))
  message("and title 'orderly deploy' and select 'Allow write access'")
}


main <- function() {
  add_deploy_key()
  invisible()
}


main()